version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sleepify
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    build: .
    environment:
      DJANGO_ENV: production
      POSTGRES_DB: db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sleepify
      POSTGRES_HOST: db
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    command: >
      sh -c "python manage.py migrate && 
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    depends_on:
      - db
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/staticfiles
    depends_on:
      - app
    networks:
      - mynetwork

volumes:
  postgres_data:
  static_volume:

networks:
  mynetwork:
